import '../globals.css'
import Link from 'next/link'
import { getPages } from '@/sanity/sanity-utils'

export const metadata = {
  title: 'My Personal Site',
  description: 'Generated by NextJs and Sanity.io',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  const pages = await getPages()
  return (
    <html lang="en">
      <body className='max-w-3xl mx-auto py-10'>
        <header className={`flex items-center justify-between`}>
          <Link href='/'
          className = {`font-bold text-2xl bg-gradient-to-r bg-clip-text
          text-transparent from-red-500 to-blue-600 hover:text-blue-500 transition duration-500 active:text-blue-200`}>
            Erick
          </Link>
          <div className = {`flex items-center gap-5 text-sm text-gray-300 font-semibold hover:text-white hover:underline underline-offset-1 transition duration-500`}>
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`}>
                {page.title}
              </Link>
            ))}
          </div>

        </header>
        <main className={`p-20`}>{children}</main>
      </body>
    </html>
  )
}
